name: Build (Gradle)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Проверяет gradle-wrapper.jar на целостность/безопасность
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Кешируем Gradle (ускоряет последующие сборки)
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x gradlew

      # Полная сборка с расширенными логами
      - name: Gradle Build
        run: ./gradlew clean build --no-daemon --stacktrace --info

      # Доп. диагностические отчёты в файлы
      - name: Dump dependencies tree
        run: |
          ./gradlew :dependencies > deps.txt || true
          echo "Java version:" > env.txt
          java -version >> env.txt 2>&1
          echo "Gradle version:" >> env.txt
          ./gradlew --version >> env.txt

      # Сохраняем артефакты (jars и логи) к ранeра
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/libs/**
            deps.txt
            env.txt
            **/build/reports/**/*
          if-no-files-found: warn
